### PR TITLE
Remove middleware hard dependency on FreeRTOS logging

### PR DESCRIPTION
**Pull request by hihigupt**

### CODE REVIEW

**Comment by danewalton** [comment]
I was just going to talk to you about this tomorrow haha

**Comment by hihigupt** [comment]
> I was just going to talk to you about this tomorrow haha

Cool now you can review/approve it ...:D

**Review by tawalke — COMMENTED** [review]
Looks good.  We should make sure we put in the config values needed for customers to use FreeRTOS logging or Azure Logging like we discussed.

**Review by tawalke — APPROVED** [review]
Good to go. Just make sure we do the info for values for customers to have the desired logging method.

**Comment by hihigupt** [comment]
> Looks good. We should make sure we put in the config values needed for customers to use FreeRTOS logging or Azure Logging like we discussed.

I have created issue to track this request.
https://github.com/Azure/azure-iot-middleware-freertos/issues/101

**Review by danewalton — APPROVED** [review]

**Pull request merged**
