### PR TITLE
Add NXP port for IoT sample

### PR DESCRIPTION
**Pull request by hihigupt**

### CODE REVIEW

**Review by tawalke — COMMENTED** [review]
@hihigupt Hi, are these files for using LWIP from the NXP repo or FreeRTOS repo? Wasn't sure where to look as reference. Are the solely copied as is or did you make changes?

**Comment by hihigupt** [comment]
@tawalke 
Files modified and added are 
https://github.com/Azure/azure-iot-middleware-freertos/blob/develop_higupt_sdk/demo/Common/mimxrt1060/transport/sockets_wrapper.c
https://github.com/Azure/azure-iot-middleware-freertos/blob/develop_higupt_sdk/demo/Common/mimxrt1060/main.c
https://github.com/Azure/azure-iot-middleware-freertos/tree/develop_higupt_sdk/demo/sample_azure_iot_embedded_sdk/mimxrt1060

**Comment by hihigupt** [comment]
Rest files are from NXP, LWIP and FreeRTOS, without anychange

**Review by danewalton — COMMENTED** [review]
I'm going to be honest, I think I can only assume this to be correct. Nit is can we maybe have one PR which merges all the "copied" code in and the other after which is the sample code which we are probably more interested in?

**Comment by tawalke** [comment]
> @tawalke
> Files modified and added are
> https://github.com/Azure/azure-iot-middleware-freertos/blob/develop_higupt_sdk/demo/Common/mimxrt1060/transport/sockets_wrapper.c
> https://github.com/Azure/azure-iot-middleware-freertos/blob/develop_higupt_sdk/demo/Common/mimxrt1060/main.c
> https://github.com/Azure/azure-iot-middleware-freertos/tree/develop_higupt_sdk/demo/sample_azure_iot_embedded_sdk/mimxrt1060

Okay I will check it out on tomorrow & look at those files. Thanks.

**Comment by hihigupt** [comment]
> I'm going to be honest, I think I can only assume t

I like this idea, let me divide this PR into two PR's
1. All nxp/lwip code copied.
2. Middleware port specific code.

**Pull request closed without merging**
